// data.js
const ALL_ITEMS = [
  // --- LEGENDARY (Difficulty 4) ---
  { id: "a150", title: "Frieden gemacht", rarity: "legendary", difficulty: 4 },
  { id: "a151", title: "Sich akzeptiert", rarity: "legendary", difficulty: 4 },
  { id: "a152", title: "Sich verstanden gefühlt", rarity: "legendary", difficulty: 4 },
  { id: "a153", title: "Sich selbst verziehen", rarity: "legendary", difficulty: 4 },
  { id: "a154", title: "Heute genug", rarity: "legendary", difficulty: 4 },
  { id: "a155", title: "Weitergemacht trotz allem", rarity: "legendary", difficulty: 4 },
  { id: "a156", title: "Sich wiedergefunden", rarity: "legendary", difficulty: 4 },
  { id: "a157", title: "Einen Tag getragen", rarity: "legendary", difficulty: 4 },
  { id: "a158", title: "Den Moment ausgehalten", rarity: "legendary", difficulty: 4 },
  { id: "a159", title: "Sich selbst begegnet", rarity: "legendary", difficulty: 4 },
  { id: "a160", title: "Nicht kaputt gegangen", rarity: "legendary", difficulty: 4 },
  { id: "a161", title: "Noch hier", rarity: "legendary", difficulty: 4 },

  // --- ULTRA (Difficulty 3) ---
  { id: "a130", title: "Sich kurz frei gefühlt", rarity: "ultra", difficulty: 3 },
  { id: "a131", title: "Sich selbst erlaubt", rarity: "ultra", difficulty: 3 },
  { id: "a132", title: "Einfach dagewesen", rarity: "ultra", difficulty: 3 },
  { id: "a133", title: "Fokus wirklich gehalten", rarity: "ultra", difficulty: 3 },
  { id: "a134", title: "Sich selbst geschont", rarity: "ultra", difficulty: 3 },
  { id: "a135", title: "Sich selbst gefordert", rarity: "ultra", difficulty: 3 },
  { id: "a136", title: "Mut gehabt", rarity: "ultra", difficulty: 3 },
  { id: "a137", title: "Ruhe gespürt", rarity: "ultra", difficulty: 3 },
  { id: "a138", title: "Kurz glücklich", rarity: "ultra", difficulty: 3 },
  { id: "a139", title: "Ganz bei sich", rarity: "ultra", difficulty: 3 },
  { id: "a140", title: "Angekommen", rarity: "ultra", difficulty: 3 },
  { id: "a141", title: "Still durchgehalten", rarity: "ultra", difficulty: 3 },
  { id: "a142", title: "Sich nicht verloren", rarity: "ultra", difficulty: 3 },

  // --- RARE (Difficulty 2) ---
  { id: "a090", title: "Sich gesammelt", rarity: "rare", difficulty: 2 },
  { id: "a091", title: "Einen Gedanken zu Ende gedacht", rarity: "rare", difficulty: 2 },
  { id: "a092", title: "Sich beruhigt", rarity: "rare", difficulty: 2 },
  { id: "a093", title: "Gedanken sortiert", rarity: "rare", difficulty: 2 },
  { id: "a094", title: "Chaos akzeptiert", rarity: "rare", difficulty: 2 },
  { id: "a095", title: "Nicht alles geschafft", rarity: "rare", difficulty: 2 },
  { id: "a096", title: "Trotzdem weitergemacht", rarity: "rare", difficulty: 2 },
  { id: "a097", title: "Sich Mühe gegeben", rarity: "rare", difficulty: 2 },
  { id: "a098", title: "Es versucht", rarity: "rare", difficulty: 2 },
  { id: "a099", title: "Heute gereicht", rarity: "rare", difficulty: 2 },
  { id: "a100", title: "Sich überfordert gefühlt", rarity: "rare", difficulty: 2 },
  { id: "a101", title: "Zweifel gehabt", rarity: "rare", difficulty: 2 },
  { id: "a102", title: "Hoffnung gespürt", rarity: "rare", difficulty: 2 },
  { id: "a103", title: "Plan gemacht", rarity: "rare", difficulty: 2 },
  { id: "a104", title: "Improvisiert", rarity: "rare", difficulty: 2 },
  { id: "a105", title: "Durchgezogen", rarity: "rare", difficulty: 2 },
  { id: "a106", title: "Drangeblieben", rarity: "rare", difficulty: 2 },
  { id: "a107", title: "Losgelassen", rarity: "rare", difficulty: 2 },
  { id: "a108", title: "Geduld gefunden", rarity: "rare", difficulty: 2 },
  { id: "a109", title: "Sich erklärt", rarity: "rare", difficulty: 2 },
  { id: "a110", title: "Sich selbst überrascht", rarity: "rare", difficulty: 2 },
  { id: "a111", title: "Leichter als gedacht", rarity: "rare", difficulty: 2 },
  { id: "a112", title: "Schwerer als erwartet", rarity: "rare", difficulty: 2 },
  { id: "a113", title: "Sich selbst ernst genommen", rarity: "rare", difficulty: 2 },
  { id: "a114", title: "Kurz stolz gewesen", rarity: "rare", difficulty: 2 },
  { id: "a115", title: "Einen Schritt gemacht", rarity: "rare", difficulty: 2 },
  { id: "a116", title: "Trotzdem okay", rarity: "rare", difficulty: 2 },
  { id: "a117", title: "Zeit gewonnen", rarity: "rare", difficulty: 2 },
  { id: "a118", title: "Leise gedacht", rarity: "rare", difficulty: 2 },

  // --- COMMON (Difficulty 1) ---
  { id: "a001", title: "Aufgestanden", rarity: "common", difficulty: 1 },
  { id: "a002", title: "Wasser getrunken", rarity: "common", difficulty: 1 },
  { id: "a003", title: "Etwas gegessen", rarity: "common", difficulty: 1 },
  { id: "a004", title: "Kurz gesessen", rarity: "common", difficulty: 1 },
  { id: "a005", title: "Tief durchgeatmet", rarity: "common", difficulty: 1 },
  { id: "a006", title: "Fenster geöffnet", rarity: "common", difficulty: 1 },
  { id: "a007", title: "Augen geschlossen", rarity: "common", difficulty: 1 },
  { id: "a008", title: "Müde gewesen", rarity: "common", difficulty: 1 },
  { id: "a009", title: "Wach geworden", rarity: "common", difficulty: 1 },
  { id: "a010", title: "Kurz bewegt", rarity: "common", difficulty: 1 },
  { id: "a011", title: "Pause gemacht", rarity: "common", difficulty: 1 },
  { id: "a012", title: "Nachgedacht", rarity: "common", difficulty: 1 },
  { id: "a013", title: "Nicht sofort reagiert", rarity: "common", difficulty: 1 },
  { id: "a014", title: "Weitergemacht", rarity: "common", difficulty: 1 },
  { id: "a015", title: "E-Mails überprüft", rarity: "common", difficulty: 1 },
  { id: "a016", title: "Nachricht beantwortet", rarity: "common", difficulty: 1 },
  { id: "a017", title: "Tab geschlossen", rarity: "common", difficulty: 1 },
  { id: "a018", title: "Zu lange gescrollt", rarity: "common", difficulty: 1 },
  { id: "a019", title: "Etwas gesucht", rarity: "common", difficulty: 1 },
  { id: "a020", title: "Etwas gefunden", rarity: "common", difficulty: 1 },
  { id: "a021", title: "App geöffnet", rarity: "common", difficulty: 1 },
  { id: "a022", title: "App wieder geschlossen", rarity: "common", difficulty: 1 },
  { id: "a023", title: "Müll rausgebracht", rarity: "common", difficulty: 1 },
  { id: "a024", title: "Licht ausgeschaltet", rarity: "common", difficulty: 1 },
  { id: "a025", title: "Etwas weggelegt", rarity: "common", difficulty: 1 },
  { id: "a026", title: "Kurz aufgeräumt", rarity: "common", difficulty: 1 },
  { id: "a027", title: "Raum gewechselt", rarity: "common", difficulty: 1 },
  { id: "a028", title: "Existiert heute", rarity: "common", difficulty: 1 },
  { id: "a029", title: "Angefangen", rarity: "common", difficulty: 1 },
  { id: "a030", title: "Wieder aufgehört", rarity: "common", difficulty: 1 },
  { id: "a031", title: "Etwas verschoben", rarity: "common", difficulty: 1 },
  { id: "a032", title: "Fokus verloren", rarity: "common", difficulty: 1 },
  { id: "a033", title: "Fokus gefunden", rarity: "common", difficulty: 1 },
  { id: "a034", title: "Nachricht gelesen", rarity: "common", difficulty: 1 },
  { id: "a035", title: "Gelächelt", rarity: "common", difficulty: 1 },
  { id: "a036", title: "Genervt gewesen", rarity: "common", difficulty: 1 },
  { id: "a037", title: "Kurz gelacht", rarity: "common", difficulty: 1 },
  { id: "a038", title: "Zeit vergessen", rarity: "common", difficulty: 1 },
  { id: "a039", title: "Auf die Uhr geschaut", rarity: "common", difficulty: 1 },
  { id: "a040", title: "Gewartet", rarity: "common", difficulty: 1 },
  { id: "a041", title: "Still geworden", rarity: "common", difficulty: 1 },
  { id: "a042", title: "Nichts gedacht", rarity: "common", difficulty: 1 },
  { id: "a043", title: "Kurz gefroren", rarity: "common", difficulty: 1 },
  { id: "a044", title: "Socken angezogen", rarity: "common", difficulty: 1 },
  { id: "a045", title: "Schlüssel gesucht", rarity: "common", difficulty: 1 },
  { id: "a046", title: "Tür abgeschlossen", rarity: "common", difficulty: 1 },
  { id: "a047", title: "Tasche gepackt", rarity: "common", difficulty: 1 },
  { id: "a048", title: "Jacke angezogen", rarity: "common", difficulty: 1 },
  { id: "a049", title: "Treppe gelaufen", rarity: "common", difficulty: 1 },
  { id: "a050", title: "Kurz gewartet", rarity: "common", difficulty: 1 },
  { id: "a051", title: "Himmel angesehen", rarity: "common", difficulty: 1 },
  { id: "a052", title: "Einatmen", rarity: "common", difficulty: 1 },
  { id: "a053", title: "Ausatmen", rarity: "common", difficulty: 1 },
  { id: "a054", title: "Warm geduscht", rarity: "common", difficulty: 1 },
  { id: "a055", title: "Zähne geputzt", rarity: "common", difficulty: 1 },
  { id: "a056", title: "Gesicht gewaschen", rarity: "common", difficulty: 1 },
  { id: "a057", title: "Creme benutzt", rarity: "common", difficulty: 1 },
  { id: "a058", title: "Spiegel geschaut", rarity: "common", difficulty: 1 },
  { id: "a059", title: "Handy geladen", rarity: "common", difficulty: 1 },
  { id: "a060", title: "Akku leer", rarity: "common", difficulty: 1 },
  { id: "a061", title: "Akku voll", rarity: "common", difficulty: 1 },
  { id: "a062", title: "WLAN an", rarity: "common", difficulty: 1 },
  { id: "a063", title: "WLAN aus", rarity: "common", difficulty: 1 },
  { id: "a064", title: "Stumm geschaltet", rarity: "common", difficulty: 1 },
  { id: "a065", title: "Vibrieren gespürt", rarity: "common", difficulty: 1 },
  { id: "a066", title: "Klingeln gehört", rarity: "common", difficulty: 1 },
  { id: "a067", title: "Link geklickt", rarity: "common", difficulty: 1 },
  { id: "a068", title: "Seite geladen", rarity: "common", difficulty: 1 },
  { id: "a069", title: "Error gesehen", rarity: "common", difficulty: 1 },
  { id: "a070", title: "Neu geladen", rarity: "common", difficulty: 1 },
  { id: "a071", title: "Gekocht", rarity: "common", difficulty: 1 },
  { id: "a072", title: "Teller abgewaschen", rarity: "common", difficulty: 1 },
  { id: "a073", title: "Krümel weggewischt", rarity: "common", difficulty: 1 },
  { id: "a074", title: "Dose aufgemacht", rarity: "common", difficulty: 1 },
  { id: "a075", title: "Flasche zugeschraubt", rarity: "common", difficulty: 1 },
  { id: "a076", title: "Glas gefüllt", rarity: "common", difficulty: 1 },
  { id: "a077", title: "Leer getrunken", rarity: "common", difficulty: 1 },
  { id: "a078", title: "Satt geworden", rarity: "common", difficulty: 1 },
  { id: "a079", title: "Hunger gehabt", rarity: "common", difficulty: 1 },
  { id: "a080", title: "Durst gehabt", rarity: "common", difficulty: 1 },
  { id: "a081", title: "Schuhe ausgezogen", rarity: "common", difficulty: 1 },
  { id: "a082", title: "Bequem gemacht", rarity: "common", difficulty: 1 },
  { id: "a083", title: "Decke genommen", rarity: "common", difficulty: 1 },
  { id: "a084", title: "Kissen gedreht", rarity: "common", difficulty: 1 },
  { id: "a085", title: "Licht an", rarity: "common", difficulty: 1 }
];
